// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.1.87.0. www.xsd2code.com
//    {"TargetFramework":11,"NameSpace":"Entities.Tutorial","Properties":{},"XmlAttribute":{"Enabled":true},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Entities.Tutorial
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlRootAttribute("aelliusconnector", Namespace="", IsNullable=false)]
    public partial class BusinessDocument
    {
        #region Private fields
        private ProcessSettings _processsettings;
        private Document _document;
        #endregion
        
        public BusinessDocument()
        {
            _document = new Document();
            _processsettings = new ProcessSettings();
        }
        
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProcessSettings processsettings
        {
            get
            {
                return _processsettings;
            }
            set
            {
                _processsettings = value;
            }
        }
        
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Document document
        {
            get
            {
                return _document;
            }
            set
            {
                _document = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessSettings
    {
        #region Private fields
        private string _aelliusrequestid;
        private string _environment;
        private bool _debug;
        private ProcessSettingsProcessmode _processmode;
        private ushort _timeout;
        private bool _anonymous;
        private string _e1user;
        private string _e1role;
        private bool _keeprepository;
        private string _lynxapp;
        private string _lynxuser;
        private string _lynxusername;
        private List<System.Xml.XmlAttribute> _anyAttr;
        #endregion
        
        public ProcessSettings()
        {
            _anyAttr = new List<System.Xml.XmlAttribute>();
        }
        
        [XmlAttribute]
        public string aelliusrequestid
        {
            get
            {
                return _aelliusrequestid;
            }
            set
            {
                _aelliusrequestid = value;
            }
        }
        
        [XmlAttribute]
        public string environment
        {
            get
            {
                return _environment;
            }
            set
            {
                _environment = value;
            }
        }
        
        [XmlAttribute]
        public bool debug
        {
            get
            {
                return _debug;
            }
            set
            {
                _debug = value;
            }
        }
        
        [XmlAttribute]
        public ProcessSettingsProcessmode processmode
        {
            get
            {
                return _processmode;
            }
            set
            {
                _processmode = value;
            }
        }
        
        [XmlAttribute]
        public ushort timeout
        {
            get
            {
                return _timeout;
            }
            set
            {
                _timeout = value;
            }
        }
        
        [XmlAttribute]
        public bool anonymous
        {
            get
            {
                return _anonymous;
            }
            set
            {
                _anonymous = value;
            }
        }
        
        [XmlAttribute]
        public string e1user
        {
            get
            {
                return _e1user;
            }
            set
            {
                _e1user = value;
            }
        }
        
        [XmlAttribute]
        public string e1role
        {
            get
            {
                return _e1role;
            }
            set
            {
                _e1role = value;
            }
        }
        
        [XmlAttribute]
        public bool keeprepository
        {
            get
            {
                return _keeprepository;
            }
            set
            {
                _keeprepository = value;
            }
        }
        
        [XmlAttribute]
        public string lynxapp
        {
            get
            {
                return _lynxapp;
            }
            set
            {
                _lynxapp = value;
            }
        }
        
        [XmlAttribute]
        public string lynxuser
        {
            get
            {
                return _lynxuser;
            }
            set
            {
                _lynxuser = value;
            }
        }
        
        [XmlAttribute]
        public string lynxusername
        {
            get
            {
                return _lynxusername;
            }
            set
            {
                _lynxusername = value;
            }
        }
        
        [XmlAnyAttributeAttribute()]
        public List<System.Xml.XmlAttribute> AnyAttr
        {
            get
            {
                return _anyAttr;
            }
            set
            {
                _anyAttr = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [XmlTypeAttribute(AnonymousType=true)]
    public enum ProcessSettingsProcessmode
    {
        @object,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressRecord
    {
        #region Private fields
        private string _name;
        private string _line1;
        private string _line2;
        private string _line3;
        private string _line4;
        private string _city;
        private string _state;
        private string _zip;
        #endregion
        
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
        
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Line1
        {
            get
            {
                return _line1;
            }
            set
            {
                _line1 = value;
            }
        }
        
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Line2
        {
            get
            {
                return _line2;
            }
            set
            {
                _line2 = value;
            }
        }
        
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Line3
        {
            get
            {
                return _line3;
            }
            set
            {
                _line3 = value;
            }
        }
        
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Line4
        {
            get
            {
                return _line4;
            }
            set
            {
                _line4 = value;
            }
        }
        
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City
        {
            get
            {
                return _city;
            }
            set
            {
                _city = value;
            }
        }
        
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string State
        {
            get
            {
                return _state;
            }
            set
            {
                _state = value;
            }
        }
        
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zip
        {
            get
            {
                return _zip;
            }
            set
            {
                _zip = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Input
    {
        #region Private fields
        private string _nameAlpha;
        #endregion
        
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NameAlpha
        {
            get
            {
                return _nameAlpha;
            }
            set
            {
                _nameAlpha = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Document
    {
        #region Private fields
        private Input _input;
        private List<AddressRecord> _output;
        private bool _success;
        #endregion
        
        public Document()
        {
            _output = new List<AddressRecord>();
            _input = new Input();
        }
        
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Input input
        {
            get
            {
                return _input;
            }
            set
            {
                _input = value;
            }
        }
        
        [XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("Address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public List<AddressRecord> output
        {
            get
            {
                return _output;
            }
            set
            {
                _output = value;
            }
        }
        
        [XmlAttribute]
        public bool success
        {
            get
            {
                return _success;
            }
            set
            {
                _success = value;
            }
        }
    }
}
#pragma warning restore
